name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: bufbuild/buf-action@v1
        with:
          lint: true
          breaking: ${{ github.event_name == 'pull_request' }}
          format: false
          push: false
